title:              Chirping Tech
email:              mbailey@paloaltonetworks.com
description:        Cloud, cyber, cheesesteaks? Random thoughts unworthy of a corporate medium.
author:             Michael Bailey
baseurl:            "/blog"
url:                "https://michaelbailey.co"

# Social Profiles
twitter_username:   
github_username:    mike-bailey
facebook_username:  mikebailey97
instagram_username: mikebailey97  
linkedin_username: cybermichael

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
